"""Add EigenschaftDefinition, Produkt, EigenschaftWert tables for PRD-009

Revision ID: 0a8a1f543f8e
Revises: ffa7e6fe81a2
Create Date: 2025-12-28 19:32:40.633413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8a1f543f8e'
down_revision = 'ffa7e6fe81a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eigenschaft_definition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ntg_code', sa.String(length=15), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('datentyp', sa.String(length=20), nullable=False),
    sa.Column('max_laenge', sa.Integer(), nullable=True),
    sa.Column('dezimalstellen', sa.Integer(), nullable=True),
    sa.Column('codelist_kategorie', sa.String(length=50), nullable=True),
    sa.Column('gruppe', sa.String(length=50), nullable=True),
    sa.Column('sortierung', sa.Integer(), nullable=True),
    sa.Column('pflichtfeld', sa.Boolean(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eigenschaft_definition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eigenschaft_definition_gruppe'), ['gruppe'], unique=False)
        batch_op.create_index(batch_op.f('ix_eigenschaft_definition_ntg_code'), ['ntg_code'], unique=True)

    op.create_table('produkt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ean', sa.String(length=14), nullable=False),
    sa.Column('artikelnummer_lieferant', sa.String(length=35), nullable=True),
    sa.Column('artikelnummer_hersteller', sa.String(length=35), nullable=True),
    sa.Column('lieferant_id', sa.Integer(), nullable=True),
    sa.Column('gln_lieferant', sa.String(length=13), nullable=True),
    sa.Column('artikelbezeichnung', sa.String(length=250), nullable=False),
    sa.Column('kurzbezeichnung', sa.String(length=35), nullable=True),
    sa.Column('hersteller_name', sa.String(length=35), nullable=True),
    sa.Column('markenname', sa.String(length=35), nullable=True),
    sa.Column('serienname', sa.String(length=35), nullable=True),
    sa.Column('uvpe', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('ekp_netto', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('mwst_satz', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('waehrung', sa.String(length=3), nullable=True),
    sa.Column('stueck_laenge_cm', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('stueck_breite_cm', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('stueck_hoehe_cm', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('stueck_gewicht_kg', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('attributgruppe_id', sa.Integer(), nullable=True),
    sa.Column('zolltarif_nr', sa.String(length=11), nullable=True),
    sa.Column('ursprungsland', sa.String(length=2), nullable=True),
    sa.Column('status', sa.String(length=15), nullable=True),
    sa.Column('lieferbar_ab', sa.Date(), nullable=True),
    sa.Column('lieferbar_bis', sa.Date(), nullable=True),
    sa.Column('erste_auslieferung', sa.Date(), nullable=True),
    sa.Column('b2c_text', sa.Text(), nullable=True),
    sa.Column('b2b_kurztext', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attributgruppe_id'], ['attributgruppe.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['lieferant_id'], ['lieferant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produkt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produkt_artikelnummer_lieferant'), ['artikelnummer_lieferant'], unique=False)
        batch_op.create_index(batch_op.f('ix_produkt_ean'), ['ean'], unique=True)

    op.create_table('eigenschaft_wert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produkt_id', sa.Integer(), nullable=False),
    sa.Column('definition_id', sa.Integer(), nullable=False),
    sa.Column('wert_text', sa.Text(), nullable=True),
    sa.Column('wert_number', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('wert_integer', sa.Integer(), nullable=True),
    sa.Column('wert_boolean', sa.Boolean(), nullable=True),
    sa.Column('wert_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['definition_id'], ['eigenschaft_definition.id'], ),
    sa.ForeignKeyConstraint(['produkt_id'], ['produkt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produkt_id', 'definition_id', name='uq_eigenschaft_wert')
    )
    with op.batch_alter_table('eigenschaft_wert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eigenschaft_wert_definition_id'), ['definition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_eigenschaft_wert_produkt_id'), ['produkt_id'], unique=False)

    # NOTE: Removed kunde table changes - not related to PRD-009
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: Removed kunde table changes - not related to PRD-009

    with op.batch_alter_table('eigenschaft_wert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eigenschaft_wert_produkt_id'))
        batch_op.drop_index(batch_op.f('ix_eigenschaft_wert_definition_id'))

    op.drop_table('eigenschaft_wert')
    with op.batch_alter_table('produkt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produkt_ean'))
        batch_op.drop_index(batch_op.f('ix_produkt_artikelnummer_lieferant'))

    op.drop_table('produkt')
    with op.batch_alter_table('eigenschaft_definition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eigenschaft_definition_ntg_code'))
        batch_op.drop_index(batch_op.f('ix_eigenschaft_definition_gruppe'))

    op.drop_table('eigenschaft_definition')
    # ### end Alembic commands ###
