"""Add logo_thumb to Verband

Revision ID: 18e97dddcbd2
Revises: 83fb130f846b
Create Date: 2025-12-11 21:56:42.595736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18e97dddcbd2'
down_revision = '83fb130f846b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verband', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_thumb', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verband', schema=None) as batch_op:
        batch_op.drop_column('logo_thumb')

    # ### end Alembic commands ###
