"""Add telefon and email to Kunde

Revision ID: 42dc07279ebb
Revises: 5a2f11a9eed5
Create Date: 2025-12-22 17:05:32.273552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42dc07279ebb'
down_revision = '5a2f11a9eed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=200), nullable=True))
        # Note: Skipping index/constraint changes - user_id unique constraint already exists

    # Note: Skipping modul.typ nullable change - not relevant to this migration

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.drop_column('email')
        batch_op.drop_column('telefon')

    # ### end Alembic commands ###
