"""Add handelsregister_info and umsatzsteuer_id to Kunde for PRD-013

Revision ID: 5a469e9dca89
Revises: 008c5f01f9c7
Create Date: 2026-01-14 18:22:07.510593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a469e9dca89'
down_revision = '008c5f01f9c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.add_column(sa.Column('handelsregister_info', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('umsatzsteuer_id', sa.String(length=50), nullable=True))
        # Note: Removed auto-detected index changes (not part of PRD-013)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.drop_column('umsatzsteuer_id')
        batch_op.drop_column('handelsregister_info')

    # ### end Alembic commands ###
