"""Modul erweitern, ModulZugriff erstellen

Revision ID: 7942480f431a
Revises: b59048200513
Create Date: 2025-12-12 16:34:22.956959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7942480f431a'
down_revision = 'b59048200513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modul_zugriff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modul_id', sa.Integer(), nullable=False),
    sa.Column('rolle_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['modul_id'], ['modul.id'], ),
    sa.ForeignKeyConstraint(['rolle_id'], ['rolle.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('modul_id', 'rolle_id', name='uq_modul_rolle')
    )
    with op.batch_alter_table('modul', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beschreibung', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('color_hex', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('route_endpoint', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('zeige_dashboard', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modul', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('zeige_dashboard')
        batch_op.drop_column('sort_order')
        batch_op.drop_column('route_endpoint')
        batch_op.drop_column('color_hex')
        batch_op.drop_column('color')
        batch_op.drop_column('icon')
        batch_op.drop_column('beschreibung')

    op.drop_table('modul_zugriff')
    # ### end Alembic commands ###
