"""Add Branche, Verband models and extend Kunde with ev_kdnr and address fields

Revision ID: 83fb130f846b
Revises: c0e17f1133d6
Create Date: 2025-12-09 17:22:21.690144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83fb130f846b'
down_revision = 'c0e17f1133d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: branche, verband, kunde_branche, kunde_verband tables already exist
    # (created via flask seed). Only add the missing kunde columns.

    # Add new columns to kunde table
    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ev_kdnr', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('strasse', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('plz', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('ort', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('land', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint('uq_kunde_ev_kdnr', ['ev_kdnr'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Only removes kunde columns (branche/verband tables are kept)

    # Remove kunde columns
    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.drop_constraint('uq_kunde_ev_kdnr', type_='unique')
        batch_op.drop_column('land')
        batch_op.drop_column('ort')
        batch_op.drop_column('plz')
        batch_op.drop_column('strasse')
        batch_op.drop_column('ev_kdnr')

    # ### end Alembic commands ###
