"""PRD-006 Kunden-Dialog: PasswordToken, Fragebogen, Teilnahme, Antwort + Kunde.user_id

Revision ID: 855ad509f342
Revises: 4c96ac535cca
Create Date: 2025-12-15 19:54:54.054613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855ad509f342'
down_revision = '4c96ac535cca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # PasswordToken - for secure one-time password reveal
    op.create_table('password_token',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(length=64), nullable=False),
        sa.Column('password_plain', sa.String(length=100), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('revealed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_token_token', 'password_token', ['token'], unique=True)

    # Fragebogen - questionnaire definition
    op.create_table('fragebogen',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('titel', sa.String(length=200), nullable=False),
        sa.Column('beschreibung', sa.Text(), nullable=True),
        sa.Column('definition_json', sa.JSON(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('erstellt_von_id', sa.Integer(), nullable=False),
        sa.Column('erstellt_am', sa.DateTime(), nullable=True),
        sa.Column('aktiviert_am', sa.DateTime(), nullable=True),
        sa.Column('geschlossen_am', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['erstellt_von_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    # FragebogenTeilnahme - customer participation with magic-link
    op.create_table('fragebogen_teilnahme',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('fragebogen_id', sa.Integer(), nullable=False),
        sa.Column('kunde_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('eingeladen_am', sa.DateTime(), nullable=True),
        sa.Column('gestartet_am', sa.DateTime(), nullable=True),
        sa.Column('abgeschlossen_am', sa.DateTime(), nullable=True),
        sa.Column('einladung_gesendet_am', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['fragebogen_id'], ['fragebogen.id'], ),
        sa.ForeignKeyConstraint(['kunde_id'], ['kunde.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('fragebogen_id', 'kunde_id', name='uq_fragebogen_kunde')
    )
    op.create_index('ix_fragebogen_teilnahme_token', 'fragebogen_teilnahme', ['token'], unique=True)

    # FragebogenAntwort - answers to questions
    op.create_table('fragebogen_antwort',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('teilnahme_id', sa.Integer(), nullable=False),
        sa.Column('frage_id', sa.String(length=50), nullable=False),
        sa.Column('antwort_json', sa.JSON(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['teilnahme_id'], ['fragebogen_teilnahme.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('teilnahme_id', 'frage_id', name='uq_teilnahme_frage')
    )

    # Kunde.user_id - link customer to user account
    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_kunde_user_id', ['user_id'])
        batch_op.create_foreign_key('fk_kunde_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('modul', schema=None) as batch_op:
        batch_op.alter_column('typ',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'basis'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop in reverse order of creation
    op.drop_table('fragebogen_antwort')
    op.drop_index('ix_fragebogen_teilnahme_token', table_name='fragebogen_teilnahme')
    op.drop_table('fragebogen_teilnahme')
    op.drop_table('fragebogen')
    op.drop_index('ix_password_token_token', table_name='password_token')
    op.drop_table('password_token')

    with op.batch_alter_table('modul', schema=None) as batch_op:
        batch_op.alter_column('typ',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'basis'"))

    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.drop_constraint('fk_kunde_user_id', type_='foreignkey')
        batch_op.drop_constraint('uq_kunde_user_id', type_='unique')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
