"""Add anrede and kommunikation_stil to User

Revision ID: 941599ad1756
Revises: fcd085ac4338
Create Date: 2025-12-24 14:13:49.034369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941599ad1756'
down_revision = 'fcd085ac4338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed auto-generated kunde table changes (index/constraint)
    # These are not needed for the user anrede/kommunikation_stil feature

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anrede', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('kommunikation_stil', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('kommunikation_stil')
        batch_op.drop_column('anrede')

    # ### end Alembic commands ###
