"""Drop legacy SubApp tables

Revision ID: 972d11ba691f
Revises: 7942480f431a
Create Date: 2025-12-12 16:42:02.262849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972d11ba691f'
down_revision = '7942480f431a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sub_app_access')
    op.drop_table('sub_app')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_app',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=50), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('beschreibung', sa.VARCHAR(length=255), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('color', sa.VARCHAR(length=20), nullable=True),
    sa.Column('color_hex', sa.VARCHAR(length=7), nullable=True),
    sa.Column('route_endpoint', sa.VARCHAR(length=100), nullable=True),
    sa.Column('aktiv', sa.BOOLEAN(), nullable=True),
    sa.Column('sort_order', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sub_app_access',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sub_app_id', sa.INTEGER(), nullable=False),
    sa.Column('rolle_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['rolle_id'], ['rolle.id'], ),
    sa.ForeignKeyConstraint(['sub_app_id'], ['sub_app.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_app_id', 'rolle_id', name=op.f('uq_subapp_rolle'))
    )
    # ### end Alembic commands ###
