"""Add hauptbranche_id to Kunde

Revision ID: b59048200513
Revises: d06fa29d54ee
Create Date: 2025-12-12 15:14:45.941329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b59048200513'
down_revision = 'd06fa29d54ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hauptbranche_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_kunde_hauptbranche', 'branche', ['hauptbranche_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.drop_constraint('fk_kunde_hauptbranche', type_='foreignkey')
        batch_op.drop_column('hauptbranche_id')

    # ### end Alembic commands ###
