"""Initial migration - all models

Revision ID: c0e17f1133d6
Revises: 
Create Date: 2025-12-06 17:33:21.406485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0e17f1133d6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('beschreibung', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_key'), ['key'], unique=True)

    op.create_table('hersteller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gln', sa.String(length=13), nullable=False),
    sa.Column('vedes_id', sa.String(length=13), nullable=True),
    sa.Column('kurzbezeichnung', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hersteller', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hersteller_gln'), ['gln'], unique=True)
        batch_op.create_index(batch_op.f('ix_hersteller_vedes_id'), ['vedes_id'], unique=True)

    op.create_table('lieferant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gln', sa.String(length=13), nullable=True),
    sa.Column('vedes_id', sa.String(length=13), nullable=False),
    sa.Column('kurzbezeichnung', sa.String(length=40), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('ftp_quelldatei', sa.String(length=255), nullable=True),
    sa.Column('ftp_pfad_ziel', sa.String(length=255), nullable=True),
    sa.Column('elena_startdir', sa.String(length=50), nullable=True),
    sa.Column('elena_base_url', sa.String(length=255), nullable=True),
    sa.Column('letzte_konvertierung', sa.DateTime(), nullable=True),
    sa.Column('artikel_anzahl', sa.Integer(), nullable=True),
    sa.Column('ftp_datei_datum', sa.DateTime(), nullable=True),
    sa.Column('ftp_datei_groesse', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lieferant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lieferant_gln'), ['gln'], unique=True)
        batch_op.create_index(batch_op.f('ix_lieferant_vedes_id'), ['vedes_id'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('vorname', sa.String(length=50), nullable=False),
    sa.Column('nachname', sa.String(length=50), nullable=False),
    sa.Column('rolle', sa.String(length=20), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('marke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kurzbezeichnung', sa.String(length=40), nullable=False),
    sa.Column('gln_evendo', sa.String(length=20), nullable=False),
    sa.Column('hersteller_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hersteller_id'], ['hersteller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('marke', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_marke_gln_evendo'), ['gln_evendo'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marke', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_marke_gln_evendo'))

    op.drop_table('marke')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('lieferant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lieferant_vedes_id'))
        batch_op.drop_index(batch_op.f('ix_lieferant_gln'))

    op.drop_table('lieferant')
    with op.batch_alter_table('hersteller', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hersteller_vedes_id'))
        batch_op.drop_index(batch_op.f('ix_hersteller_gln'))

    op.drop_table('hersteller')
    with op.batch_alter_table('config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_key'))

    op.drop_table('config')
    # ### end Alembic commands ###
