"""Add kunde_benutzer junction table for 1:N relationship

Revision ID: f6d68441123e
Revises: 42dc07279ebb
Create Date: 2025-12-23 14:03:47.853129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6d68441123e'
down_revision = '42dc07279ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Create new junction table
    op.create_table('kunde_benutzer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kunde_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ist_hauptbenutzer', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kunde_id'], ['kunde.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kunde_id', 'user_id', name='uq_kunde_benutzer')
    )

    # 2. Migrate existing kunde.user_id relationships to junction table
    # Each existing relationship becomes a Hauptbenutzer entry
    connection = op.get_bind()
    connection.execute(sa.text("""
        INSERT INTO kunde_benutzer (kunde_id, user_id, ist_hauptbenutzer, created_at)
        SELECT id, user_id, 1, CURRENT_TIMESTAMP
        FROM kunde
        WHERE user_id IS NOT NULL
    """))

    # 3. Clean up kunde table index (don't remove user_id column yet for safety)
    # Note: Not modifying kunde table indexes to avoid SQLite batch issues
    # The user_id column and its constraints remain for backward compatibility

    with op.batch_alter_table('modul', schema=None) as batch_op:
        batch_op.alter_column('typ',
               existing_type=sa.VARCHAR(length=30),
               nullable=True,
               existing_server_default=sa.text("'basis'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modul', schema=None) as batch_op:
        batch_op.alter_column('typ',
               existing_type=sa.VARCHAR(length=30),
               nullable=False,
               existing_server_default=sa.text("'basis'"))

    # Note: kunde_benutzer data is not migrated back to kunde.user_id
    # After downgrade, kunde.user_id relationships need to be restored manually if needed

    op.drop_table('kunde_benutzer')
    # ### end Alembic commands ###
